production:
  domain:
  - name: "bricksco@bricksites.com"
    ssh_options:
    - "-p 2222"
  deploy_to: "~/public_html/strand.io/"
  repository: "git@github.com:micahredding/strand.git"
  branch: "master"